package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2014-06-23T12:38:47.742+05:30
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "ConvertTemperature", 
                  wsdlLocation = "file:/home/roni/Desktop/cq5.6/project/integration/integration_cq_cxf/bundle/src/main/wsdl/ConvertTemperature.wsdl",
                  targetNamespace = "http://www.webserviceX.NET/") 
public class ConvertTemperature extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.webserviceX.NET/", "ConvertTemperature");
    public final static QName ConvertTemperatureSoap = new QName("http://www.webserviceX.NET/", "ConvertTemperatureSoap");
    public final static QName ConvertTemperatureSoap12 = new QName("http://www.webserviceX.NET/", "ConvertTemperatureSoap12");
    public final static QName ConvertTemperatureHttpGet = new QName("http://www.webserviceX.NET/", "ConvertTemperatureHttpGet");
    public final static QName ConvertTemperatureHttpPost = new QName("http://www.webserviceX.NET/", "ConvertTemperatureHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/roni/Desktop/cq5.6/project/integration/integration_cq_cxf/bundle/src/main/wsdl/ConvertTemperature.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConvertTemperature.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/roni/Desktop/cq5.6/project/integration/integration_cq_cxf/bundle/src/main/wsdl/ConvertTemperature.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConvertTemperature(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConvertTemperature(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertTemperature() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConvertTemperature(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConvertTemperature(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ConvertTemperature(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConvertTemperatureSoap
     */
    @WebEndpoint(name = "ConvertTemperatureSoap")
    public ConvertTemperatureSoap getConvertTemperatureSoap() {
        return super.getPort(ConvertTemperatureSoap, ConvertTemperatureSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertTemperatureSoap
     */
    @WebEndpoint(name = "ConvertTemperatureSoap")
    public ConvertTemperatureSoap getConvertTemperatureSoap(WebServiceFeature... features) {
        return super.getPort(ConvertTemperatureSoap, ConvertTemperatureSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ConvertTemperatureSoap
     */
    @WebEndpoint(name = "ConvertTemperatureSoap12")
    public ConvertTemperatureSoap getConvertTemperatureSoap12() {
        return super.getPort(ConvertTemperatureSoap12, ConvertTemperatureSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertTemperatureSoap
     */
    @WebEndpoint(name = "ConvertTemperatureSoap12")
    public ConvertTemperatureSoap getConvertTemperatureSoap12(WebServiceFeature... features) {
        return super.getPort(ConvertTemperatureSoap12, ConvertTemperatureSoap.class, features);
    }
    /**
     *
     * @return
     *     returns ConvertTemperatureHttpGet
     */
    @WebEndpoint(name = "ConvertTemperatureHttpGet")
    public ConvertTemperatureHttpGet getConvertTemperatureHttpGet() {
        return super.getPort(ConvertTemperatureHttpGet, ConvertTemperatureHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertTemperatureHttpGet
     */
    @WebEndpoint(name = "ConvertTemperatureHttpGet")
    public ConvertTemperatureHttpGet getConvertTemperatureHttpGet(WebServiceFeature... features) {
        return super.getPort(ConvertTemperatureHttpGet, ConvertTemperatureHttpGet.class, features);
    }
    /**
     *
     * @return
     *     returns ConvertTemperatureHttpPost
     */
    @WebEndpoint(name = "ConvertTemperatureHttpPost")
    public ConvertTemperatureHttpPost getConvertTemperatureHttpPost() {
        return super.getPort(ConvertTemperatureHttpPost, ConvertTemperatureHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertTemperatureHttpPost
     */
    @WebEndpoint(name = "ConvertTemperatureHttpPost")
    public ConvertTemperatureHttpPost getConvertTemperatureHttpPost(WebServiceFeature... features) {
        return super.getPort(ConvertTemperatureHttpPost, ConvertTemperatureHttpPost.class, features);
    }

}
